sudo: required
language: python
services:
- docker
os:
- linux
before_script:
- docker --version
- docker-compose --version
script:
- docker-compose build
- docker images
- docker-compose up -d
- docker ps
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- docker push vietdien2005/php7_jenkins
notifications:
  slack:
    rooms:
      secure: A7Ly/2q31SrbE5IkhY15sStq2cF2UsG4haeallzutq80ylEdnk7H4p176vRkSHPun8cB60KYE4Xt0sYlh7tHNoSmK8Md/sEz57+AozLZij22m90MDVm8ZcU7IdbsdkJrL8tJuY85+Gg5smWPMUK+zEJR1eRbd20tkOPAucs5hk1GQlec2Zc+8x3H99e+J46MEovjLbS7wup5xtWHIRaC1GzghweVAdqNvbSp6uvOTswdWj7PDhKiMJ3ZPPWUOeNsCQmPW1saA5Ga2HtwiHd73eRAaujDE8w1UpOt5/10s+wqXzM7ty83Cc2t08L/luAbxfsqyv1Misf+2zG+AQKtiYZ+DecG/L1gdDZ21lkYXqmU7exIYlF+pk34VIAIJk72ghCneBBpgPEtbHGbahr+CNDJOWYtqXOganz0o/Wl61QnMlpyvpoGP7XyYvnZV29IPY9/9xmaIMkuwgkKBa93tVZhWV4J2LhcZ6AuIXa/relaY27nR/HSPEJuXGW4S7oxjr8olDIZQvtRzS63rzAiGztMm7UTfUsCgAvAhDx3l9prN7/27JZS1UzXTlAfNOTWPk/eQ5yFI+VGa21LRNuiZy/3+MqgMeCs/jL/4b4v+GQw2R8djl5HrDWshGyB8440b5vNImHE9JpC8kyixcPEGEpn2re8GRq0NQLkp6IAwWQ=
env:
  global:
  - secure: g2HxszCfmO1iq7SBVk85ZqUtKOJfyaYYiXDqTK0/mAWe2mo1irNPL9dvc5M4OhlckbOuhdSw/tqreb8WUD+iQ3pskpMKdCw7CNwdHLfzjIx83riWkc0FtnT0LZpJH+HTVNvKh8596hyE8x4KluC3eZbplkWIBPYKw9qYwXXjfMLhJcEWR88WFsLmyYoocZT33qqxCSVhllT8s4S6oG8mklB2F9IJemkvxArT2xPviHEijz5qRbdAUyiyM+LKR9Y9cE+TWFpPYe7ei8Hray8JyX4+zVOtcZqaRIOk9FdjS0J7GJ/+owiGe/oqJ1iwDXlNnzWBSZEeS9e/sD0VXEnQVdsHvUMDC/98A3JwkWa1UC7Sps0DlBdM/ErxhJJSC3SqDIUXI4W6T2FCm2rUuiKHGvNFcECEnMLa81MNEMWkgINg2dkPSQIyUXkiKNS83V+kZnpRS9U1m3RO8tZp7dV3/lMncbRhz1krrO5h9hRkkxptQJPl9heZ7KRgIZhArEltJtrEbjw+2tZVYaOmiFKLvhk34RXmH6gA/Khri+Xp0gOpevTSXwk68jua1Mm6E5xa3KKtJqNRxuzk7KwEACnwpXACODlr0Yeu+EvsafcEUECWa1/GuaX9lKxk4QfTHdep47HX1MId8+Tr9xlMpsSHBgyII3stxvA3BYrfrm1/kZw=
  - secure: kxPD1N1BdcROKVNFPlkyswBUF84h9xsIi6YvMYffGmknU7a7sMFpw0thjwf+8+zYNygQpjGzFRTiqs15nmlkMRXcrA40bzj9grzOc8thYWX4377vSn99kJbC4mz6ttVZqfj8Zz3eiGoiEDHhpnKJyE2ihFRq2j1VFrY4b0fl2stXV4gJ1vvYGvqnT1cpxHy8CwjrUjeyHKdq4PHL3QdOgYG7uPeJIQYtsHcdARGHmda7zeUwHWFDaJZuXfMzJFAL1yrcNqMyrnQcuajzmpKyb6FFk7z5d76JX8afjpbdT08QGe/p9N8lMX4PDtL+By+fjV3OxZJf6gEl+TaSh9DPiXZ8OnK5uDuVi6nFvmZWx0VYt4+Y8mXbE6bDcRJaYPlU30kVEdkOMLcsUMKz1C7vaIYJ+d/hgOrW7Pk9vVMQTRQhau4Msau8hRCGqmZK2KrcfG8aWdDy5PpHPJa+Zcy8eW6beQOi1gPW9Vd4KHYGrF6sHlYOJSM/QmL5VoVIgAZ4Z/XIhl/DX/EDws0Nep0G3uLUSyYYVyFdv+DXV8Ez/3r0fWvaGvikIWA6JbbkwuygcAFUT0t6L4Gs2fceAzMqyqj1jRxFu7GmBPlqRP6R3OCDlxlW3ATXRR3RswrsjoEAFtU49ne1FOmo05ySqhFUaMg+8nB1eVWRs0kD+L9cmJU=
  - secure: Dy3ADUChK/sQwTKiY6rClmF2IHE1FdEOZT+8sNUS3ADw5VJxvLErabxMdzAiUbMryZIcepJRrirIuiD5nYeu09MUSYukBDOvqUTHSeZ+hWovzBfkarKiuw3AT8/qUse2BM/eJaRz4tqFxxQzgSJHV2xell9S39sY2L7yMndVbcAQYWLIX63B2NhEqaDi8npHARfXtJve08AhW0+HEvzW9dV1irblkjaUPrBvi5r2r+HvQyHBSX5J49Nmp6cH032j3yqmVKNalUi85HKim48TKvqQszvzhlLW7z84ejGqm/+ZyKbk8k0rMe9C4y6PMOE3zUu9gtcCMhEea+EFB7/O2bnT1Jvci42brQAgQ5D5N1Y4WuwCETK0hFGnAL0fMoX9iLiWVxbrUxcIAdQ8Ww2BiwvtBiWSplAJfrbg1ydirbdVKUvs72OrRsmgBvgRxbXEgD6OW0Aip3K8rOtNSzBvNp/YfK6R05vl0pppsRRtDaq5VqhzOG4RSJj9i2vC5n9jxWkS5Z6gOKH/WWkcolgxhkjmTjBNvaFBzDptot/VE1aX+RodxW2M4zMOraSklpOZDfv+2NTsF2oWUQC7acxgEwuG97aMME82gBw2ICFPCPv2/YxIuJ1AMm0QBEbQgpL9TCJA5qrWpj3FJSzmbCMEjChDzlBgL0dn7+iY6+j4iC0=
